# apiVersion: install.istio.io/v1alpha1
# kind: IstioOperator
# spec:
#   profile: remote 
#   components:
#     ingressGateways:
#     - name: istio-ingressgateway
#       enabled: true
#     egressGateways:
#     - name: istio-egressgateway
#       enabled: true
#     crdInstallation:
#       enabled: true