 apiVersion: v1
 kind: PersistentVolumeClaim
 metadata:
   name: solana-amm-service-pvc
   namespace: support
 spec:
   accessModes:
     - ReadWriteOnce
   resources:
     requests:
       storage: 1Gi
